const n1=5;
const n2=10;


console.log(n1);

try{
   console.log(n3);
}catch(error){
 console.log(error);
}

console.log(n2);